CREATE TABLE LANGUAGE(
  ID INT PRIMARY KEY,
  NAMES CHAR(2) NOT NULL,
);

CREATE TABLE FACULTY(
  ID INT PRIMARY KEY,
  NAMES CHAR(30) NOT NULL,
  LANG INT REFERENCES LANGUAGE(ID) NOT NULL,
);

CREATE TABLE ROLES(
  ID INT PRIMARY KEY,
  NAMES CHAR(20) NOT NULL,
  LANG INT REFERENCES LANGUAGE(ID) NOT NULL,
);

CREATE TABLE STATUS(
  ID INT PRIMARY KEY,
  NAMES CHAR(20) NOT NULL,
);

CREATE TABLE JOB(
  ID INT PRIMARY KEY,
  NAME TEXT NOT NULL,
  FACULTY_ID INT REFERENCES FACULTY(ID) NOT NULL,
  ROLE_ID INT REFERENCES ROLES(ID) NOT NULL,
  STATUS_ID INT REFERENCES STATUS(ID) NOT NULL,
  TODAY DATE NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  COMPLETE BOOLEAN NOT NULL,
);
