INSERT INTO LANGUAGE(NAMES) VALUES
  ('EN'), ('FR');

INSERT INTO ROLES(NAMES, LANG) VALUES
  ('STUDENT', 1), ('TEACHING ASSISTANT', 1),
  ('PROFESSOR', 1), ('ETUDIANT(E)', 2),
  ("ASSISTANT(E) D'EDUCATION", 2), ('PROFESSEUR(E)', 2);

INSERT INTO STATUS(NAMES) VALUES
  ('FULL-TIME'), ('PART-TIME'), ('NONE OF THE ABOVE');

INSERT INTO FACULTY(NAMES, LANG) VALUES
  ('ARTS', 1), ('SOCIAL SCIENCES', 1),
  ('EDUCATION', 1), ('ENGINEERING', 1),
  ('SCIENCE', 1), ('HEALTH SCIENCE', 1),
  ('MEDICINE', 1), ('LAW & COMMON LAW', 1), ('TELFER', 1)
  ('ARTS', 2), ('SCIENCES SOCIALE', 2),
  ('EDUCATION', 2), ('GENIE', 2),
  ('SCIENCE', 2), ('SCIENCE DE LA SANTE', 2),
  ('MEDECINE', 2), ('DROIT & DROIT CIVIL', 2), ('TELFER', 2);
